version: '3.8'
name: cryptofi-frontend-coding-challenge
services:
  cryptofi-frontend-coding-challenge:
    container_name: cryptofi-frontend-coding-challenge
    build:
      context: ../..
      dockerfile: docker/config/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ../../api/src:/app/src
      - ../../docker:/app/docker
    env_file:
      - ../env/.env

  frontend:
    container_name: frontend
    build:
      context: ../..
      dockerfile: docker/config/frontend.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../../frontend:/app/frontend
      - ../../docker:/app/docker
